// lib/clickhouse/runClickhouseTriage.ts
// Decision point: mock vs real ClickHouse execution.
<<<<<<< HEAD
// For public repo / no credentials, use mock runner.
// For your VPS setup, call the Cachey Proxy behind Caddy.
=======
// For public repo / no credentials, default to mock metrics,
// BUT always return REAL SQL generated by sqlBuilder (so curl proves wiring).
>>>>>>> origin/main

import { buildClickhouseSql } from "./sqlBuilder";
import { runMockClickhouseTriage } from "./runMockClickhouseTriage";

export type ClickhouseTriageInputs = {
  partner: string;

  // Core scope filters
  service: string; // live|vod|all
  region: string;  // region|all
  pop: string;     // pop|all

  // Option B filters
  contentType: string; // manifest|segment|api|all
  uaFamily: string;    // web|mobile|...|all

  windowMinutes: number;
  debug: boolean;

  // ✅ NEW filters
  contentType: string; // all|manifest|segment|api
  uaFamily: string; // all|stb|mobile|web|smart_tv|console
};

// Canonical SQL shape (include params so runner can execute later)
export type SqlPayload = { queries: string[]; params?: Record<string, any> };

export type ClickhouseTriageResult = {
  // Canonical
  summary: string;
  metricsJson: any;
<<<<<<< HEAD
  debugSql?: string;
};

function env(name: string): string {
  return String(process.env[name] ?? "").trim();
}

function isClickhouseTriageResult(x: any): x is ClickhouseTriageResult {
  return (
    x &&
    typeof x === "object" &&
    typeof x.summaryText === "string" &&
    x.metricsJson != null
  );
=======
  evidence?: any;
  sql?: SqlPayload;

  // Legacy compatibility
  summaryText?: string;
};

// NOTE: Keep this helper only for backward compat with older mock runner outputs.
// We will NOT use it to generate SQL anymore (sqlBuilder is the source of truth).
function normalizeSql(result: any): SqlPayload | undefined {
  const q1 = result?.sql?.queries;
  if (Array.isArray(q1) && q1.length) {
    return { queries: q1.map((x: any) => String(x)), params: result?.sql?.params ?? undefined };
  }

  const dbg = result?.debugSql;
  if (typeof dbg === "string" && dbg.trim()) return { queries: [dbg.trim()] };
  if (Array.isArray(dbg) && dbg.length) return { queries: dbg.map((x: any) => String(x)) };

  return undefined;
}

// ✅ NEW: Map friendly UI partner names to DB partner IDs
function mapPartnerToDb(partner: string) {
  const p = String(partner ?? "").trim();
  const m: Record<string, string> = {
    beta_stream: "partner_01",
    // Add more mappings later if/when needed:
    // alpha_news: "partner_02",
  };
  return m[p] ?? p;
>>>>>>> origin/main
}

export async function runClickhouseTriage(
  inputs: ClickhouseTriageInputs
): Promise<ClickhouseTriageResult> {
<<<<<<< HEAD
  const proxyUrl = env("CACHEY_PROXY_URL");
  const proxyKey = env("CACHEY_PROXY_KEY");

  // Proxy path (Phase 2)
  if (proxyUrl && proxyKey) {
    const url = `${proxyUrl.replace(/\/+$/, "")}/triage`;

    // ✅ Timeout guard (default 12s; adjust later)
    const controller = new AbortController();
    const timeoutMs = Number(env("CACHEY_PROXY_TIMEOUT_MS") || 12000);
    const t = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const resp = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json",
          "X-CACHEY-KEY": proxyKey,
        },
        body: JSON.stringify(inputs),
        signal: controller.signal,
      });

      if (!resp.ok) {
        // Try JSON first
        let details = "";
        const ct = resp.headers.get("content-type") || "";
        try {
          if (ct.includes("application/json")) {
            const j = await resp.json();
            details = j?.error ? String(j.error) : JSON.stringify(j);
          } else {
            details = await resp.text();
          }
        } catch {
          // ignore
        }

        throw new Error(
          `Proxy triage failed (${resp.status} ${resp.statusText})${details ? `: ${details}` : ""}`
        );
      }

      const data = await resp.json();

      if (!isClickhouseTriageResult(data)) {
        throw new Error(
          "Proxy triage returned an invalid payload (expected {summaryText, metricsJson, debugSql?})."
        );
      }

      return data;
    } catch (e: any) {
      if (e?.name === "AbortError") {
        throw new Error(`Proxy triage timed out after ${timeoutMs}ms`);
      }
      throw e;
    } finally {
      clearTimeout(t);
    }
  }

  // Public / local fallback
  return runMockClickhouseTriage(inputs);
=======
  const dbPartner = mapPartnerToDb(inputs.partner);

  // ✅ ALWAYS build real SQL first (this removes "-- MOCK SQL" from curl output)
  const built = buildClickhouseSql({
    partner: dbPartner, // ✅ mapped partner
    service: inputs.service,
    region: inputs.region,
    pop: inputs.pop,
    contentType: inputs.contentType,
    uaFamily: inputs.uaFamily,
    windowMinutes: inputs.windowMinutes,

    // ✅ requires sqlBuilder.ts to support this optional field
    anchorToMaxTs: inputs.debug,
  } as any);

  // Later: switch to real CH runner when credentials exist.
  // Example:
  // if (process.env.CLICKHOUSE_URL) return runRealClickhouseTriage(inputs, built);

  // For now: mock metrics (public-safe) but real SQL
  const raw = await runMockClickhouseTriage(inputs);

  const summary = String(raw?.summary ?? raw?.summaryText ?? "");
  const metricsJson = raw?.metricsJson ?? null;
  const evidence = raw?.evidence ?? undefined;

  // If mock runner supplies SQL, ignore it in favor of canonical builder SQL.
  // But we keep normalizeSql() around in case you want to compare/debug later.
  const _mockSql = normalizeSql(raw);

  // ✅ annotate debug so you can verify mapping + anchoring via API output
  if (metricsJson && typeof metricsJson === "object") {
    metricsJson.debug = metricsJson.debug && typeof metricsJson.debug === "object" ? metricsJson.debug : {};
    metricsJson.debug.partner = inputs.partner;
    metricsJson.debug.dbPartner = dbPartner;
    metricsJson.debug.anchorToMaxTs = !!inputs.debug;
  }

  return {
    summary,
    metricsJson,
    evidence,
    sql: { queries: built.queries, params: built.params },
    summaryText: summary, // legacy
  };
>>>>>>> origin/main
}