// lib/clickhouse/runClickhouseTriage.ts
// Decision point: mock vs real ClickHouse execution.
// For public repo / no credentials, return mock metrics,
// BUT always return REAL SQL generated by sqlBuilder (so curl proves wiring).

import { buildClickhouseSql } from "./sqlBuilder";
import { runMockClickhouseTriage } from "./runMockClickhouseTriage";

export type ClickhouseTriageInputs = {
  partner: string;

  // Core scope filters
  service: string; // live|vod|all
  region: string;  // region|all
  pop: string;     // pop|all

  // Generator schema dims
  contentType: string; // all|manifest|segment|api
  uaFamily: string;    // all|stb|mobile|web|smart_tv|console

  windowMinutes: number;
  debug: boolean;
};

// Canonical SQL shape (include params so runner can execute later)
export type SqlPayload = { queries: string[]; params?: Record<string, any> };

export type ClickhouseTriageResult = {
  summary: string;
  metricsJson: any;
  evidence?: any;
  sql?: SqlPayload;

  // Legacy compatibility
  summaryText?: string;
};

// NOTE: Keep this helper only for backward compat with older mock runner outputs.
function normalizeSql(result: any): SqlPayload | undefined {
  const q1 = result?.sql?.queries;
  if (Array.isArray(q1) && q1.length) {
    return { queries: q1.map((x: any) => String(x)), params: result?.sql?.params ?? undefined };
  }

  const dbg = result?.debugSql;
  if (typeof dbg === "string" && dbg.trim()) return { queries: [dbg.trim()] };
  if (Array.isArray(dbg) && dbg.length) return { queries: dbg.map((x: any) => String(x)) };

  return undefined;
}

// ✅ Map friendly UI partner names to DB partner IDs (optional)
function mapPartnerToDb(partner: string) {
  const p = String(partner ?? "").trim();
  const m: Record<string, string> = {
    beta_stream: "partner_01",
    // Add more mappings later if/when needed.
  };
  return m[p] ?? p;
}

export async function runClickhouseTriage(
  inputs: ClickhouseTriageInputs
): Promise<ClickhouseTriageResult> {
  const dbPartner = mapPartnerToDb(inputs.partner);

  // 8C: dataset is backfilled/old → anchor window to max(ts) by default
  // (Later we can add a switch to use now() when ingest is real-time.)
  const anchorToMaxTs = true;

  // ✅ ALWAYS build canonical SQL first
  const built = buildClickhouseSql({
    partner: dbPartner,
    service: inputs.service,
    region: inputs.region,
    pop: inputs.pop,
    contentType: inputs.contentType,
    uaFamily: inputs.uaFamily,
    windowMinutes: inputs.windowMinutes,
    anchorToMaxTs,
  } as any);

  // Later: swap this for real ClickHouse execution.
  const raw = await runMockClickhouseTriage(inputs);

  const summary = String(raw?.summary ?? raw?.summaryText ?? "");
  const metricsJson = raw?.metricsJson ?? null;
  const evidence = raw?.evidence ?? undefined;

  // If mock runner supplies SQL, ignore it in favor of canonical builder SQL.
  const _mockSql = normalizeSql(raw);
  void _mockSql;

  // ✅ annotate debug so API output proves mapping + clock mode
  if (metricsJson && typeof metricsJson === "object") {
    const dbg =
      metricsJson.debug && typeof metricsJson.debug === "object" ? metricsJson.debug : {};
    dbg.partner = inputs.partner;
    dbg.dbPartner = dbPartner;
    dbg.anchorToMaxTs = anchorToMaxTs;
    metricsJson.debug = dbg;
  }

  return {
    summary,
    metricsJson,
    evidence,
    sql: { queries: built.queries, params: built.params },
    summaryText: summary, // legacy
  };
}