// lib/clickhouse/runClickhouseTriage.ts
// Decision point: mock vs real ClickHouse execution.
// For public repo / no credentials, default to mock metrics,
// BUT always return REAL SQL generated by sqlBuilder (so curl proves wiring).

import { buildClickhouseSql } from "./sqlBuilder";
import { runMockClickhouseTriage } from "./runMockClickhouseTriage";

export type ClickhouseTriageInputs = {
  partner: string;
  service: string;
  region: string;
  pop: string;
  windowMinutes: number;
  debug: boolean;

  // ✅ NEW filters
  contentType: string; // all|manifest|segment|api
  uaFamily: string; // all|stb|mobile|web|smart_tv|console
};

// Canonical SQL shape (include params so runner can execute later)
export type SqlPayload = { queries: string[]; params?: Record<string, any> };

export type ClickhouseTriageResult = {
  // Canonical
  summary: string;
  metricsJson: any;
  evidence?: any;
  sql?: SqlPayload;

  // Legacy compatibility
  summaryText?: string;
};

// NOTE: Keep this helper only for backward compat with older mock runner outputs.
// We will NOT use it to generate SQL anymore (sqlBuilder is the source of truth).
function normalizeSql(result: any): SqlPayload | undefined {
  const q1 = result?.sql?.queries;
  if (Array.isArray(q1) && q1.length) {
    return { queries: q1.map((x: any) => String(x)), params: result?.sql?.params ?? undefined };
  }

  const dbg = result?.debugSql;
  if (typeof dbg === "string" && dbg.trim()) return { queries: [dbg.trim()] };
  if (Array.isArray(dbg) && dbg.length) return { queries: dbg.map((x: any) => String(x)) };

  return undefined;
}

// ✅ NEW: Map friendly UI partner names to DB partner IDs
function mapPartnerToDb(partner: string) {
  const p = String(partner ?? "").trim();
  const m: Record<string, string> = {
    beta_stream: "partner_01",
    // Add more mappings later if/when needed:
    // alpha_news: "partner_02",
  };
  return m[p] ?? p;
}

export async function runClickhouseTriage(
  inputs: ClickhouseTriageInputs
): Promise<ClickhouseTriageResult> {
  const dbPartner = mapPartnerToDb(inputs.partner);

  // ✅ ALWAYS build real SQL first (this removes "-- MOCK SQL" from curl output)
  const built = buildClickhouseSql({
    partner: dbPartner, // ✅ mapped partner
    service: inputs.service,
    region: inputs.region,
    pop: inputs.pop,
    contentType: inputs.contentType,
    uaFamily: inputs.uaFamily,
    windowMinutes: inputs.windowMinutes,

    // ✅ requires sqlBuilder.ts to support this optional field
    anchorToMaxTs: inputs.debug,
  } as any);

  // Later: switch to real CH runner when credentials exist.
  // Example:
  // if (process.env.CLICKHOUSE_URL) return runRealClickhouseTriage(inputs, built);

  // For now: mock metrics (public-safe) but real SQL
  const raw = await runMockClickhouseTriage(inputs);

  const summary = String(raw?.summary ?? raw?.summaryText ?? "");
  const metricsJson = raw?.metricsJson ?? null;
  const evidence = raw?.evidence ?? undefined;

  // If mock runner supplies SQL, ignore it in favor of canonical builder SQL.
  // But we keep normalizeSql() around in case you want to compare/debug later.
  const _mockSql = normalizeSql(raw);

  // ✅ annotate debug so you can verify mapping + anchoring via API output
  if (metricsJson && typeof metricsJson === "object") {
    metricsJson.debug = metricsJson.debug && typeof metricsJson.debug === "object" ? metricsJson.debug : {};
    metricsJson.debug.partner = inputs.partner;
    metricsJson.debug.dbPartner = dbPartner;
    metricsJson.debug.anchorToMaxTs = !!inputs.debug;
  }

  return {
    summary,
    metricsJson,
    evidence,
    sql: { queries: built.queries, params: built.params },
    summaryText: summary, // legacy
  };
}